server:
  port: 8080

spring:
  application:
    name: global-coffee-enthusiasts
  datasource:
    url: jdbc:postgresql://localhost:5432/global_coffee_enthusiasts
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE